# Generated by Django 4.1.13 on 2025-02-05 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('a_admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_username', models.CharField(max_length=255, unique=True)),
                ('a_password', models.CharField(max_length=255)),
                ('a_roles', models.CharField(max_length=255)),
                ('a_hms', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=255)),
                ('d_specialty', models.CharField(max_length=255)),
                ('d_contact_no', models.CharField(max_length=15)),
                ('d_photo', models.ImageField(blank=True, null=True, upload_to='doctors_photos/')),
                ('d_age', models.IntegerField()),
                ('d_hms', models.CharField(max_length=100)),
                ('d_user_id', models.CharField(max_length=255, unique=True)),
                ('d_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=250)),
                ('p_age', models.IntegerField()),
                ('p_gender', models.CharField(max_length=10)),
                ('p_contact_no', models.CharField(max_length=15)),
                ('p_address', models.TextField()),
                ('p_blood_group', models.CharField(max_length=5)),
                ('p_photo', models.ImageField(blank=True, null=True, upload_to='patients_photos/')),
                ('p_hms', models.CharField(max_length=100)),
                ('p_user_id', models.CharField(max_length=255, unique=True)),
                ('p_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('a_appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_appointment_date', models.DateTimeField()),
                ('a_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('a_hms', models.CharField(max_length=100)),
                ('a_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.doctor')),
                ('a_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.patients')),
            ],
        ),
    ]
