# Generated by Django 5.1.6 on 2025-02-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='a_patient',
            field=models.CharField(max_length=100),
        ),
    ]
