# Generated by Django 5.1.6 on 2025-02-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_alter_appointment_a_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer not to say')], default='N', max_length=1),
        ),
    ]
