# Generated by Django 5.1.6 on 2025-02-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0003_doctor_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='gender',
            new_name='d_gender',
        ),
    ]
