# Generated by Django 5.1.6 on 2025-03-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0005_alter_doctor_d_gender_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='a_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin_photos/'),
        ),
    ]
