# Generated by Django 5.1.6 on 2025-03-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0007_operationtheater_operationschedule_delete_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='d_contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='d_user_id',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='operationschedule',
            name='theater',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='p_contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patients',
            name='p_user_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
