# Generated by Django 5.1.6 on 2025-03-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0008_alter_doctor_d_contact_no_alter_doctor_d_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationschedule',
            name='scheduled_time',
        ),
        migrations.AlterField(
            model_name='operationschedule',
            name='scheduled_date',
            field=models.DateTimeField(),
        ),
    ]
