# Generated by Django 5.1.6 on 2025-03-04 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0009_remove_operationschedule_scheduled_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='a_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.patients'),
        ),
    ]
